service: serverless-notes-app

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  myRegion: us-east-1

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ${opt:region, self:custom.myRegion}

  # Define permission for Lambda
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb: DescribeTable
        - dynamodb: Query
        - dynamodb: Scan
        - dynamodb: GetItem
        - dynamodb: PutItem
        - dynamodb: UpdateItem
        - dynamodb: DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    handler: notes/create.notes
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam

  get:
    handler: notes/get.notes
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: aws_iam

  list: 
    handler: notes/list.notes
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam

  update: 
    handler: notes/update.notes
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer: aws_iam

  delete:
    handler: notes/delete.notes
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer: aws_iam


