service: serverless-notes-app

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  myRegion: us-east-1

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ${opt:region, self:custom.myRegion}

functions:
  hello:
    handler: handler.hello
