service: serverless-notes-app

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  myRegion: us-east-1

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ${opt:region, self:custom.myRegion}

  # Define permission for Lambda
  iamRoleStatements:
    - Effect: Allow
      Allow:
        - dynamodb: DescribeTable
        - dynamodb: Query
        - dynamodb: Scan
        - dynamodb: GetItem
        - dynamodb: PutItem
        - dynamodb: UpdateItem
        - dynamodb: DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    handler: notes/create.create
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
